# Generated by Django 6.1 on 2026-08-25 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_invited', 'Not Invited'), ('invite_sent', 'Invite Sent')], default='not_invited', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_credential', models.CharField(choices=[('QR / NFC', 'QR / NFC')], default='QR / NFC', max_length=50)),
                ('secondary_credential', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DUPLICATE', 'Duplicate'), ('NOT_FOUND', 'Not Found')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credentials.employeecredential')),
            ],
        ),
    ]
