# Generated by Django 6.1 on 2026-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_invited', 'Not Invited'), ('invite_sent', 'Invite Sent')], default='not_invited', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_credential', models.CharField(choices=[('QR / NFC', 'QR / NFC')], default='QR / NFC', max_length=50)),
                ('secondary_credential', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
