# Generated by Django 6.1 on 2026-08-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecredential',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
