# Generated by Django 6.1 on 2026-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_split_primary_credential_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecredential',
            name='primary_credential',
            field=models.CharField(choices=[('QR', 'QR'), ('NFC', 'NFC')], default='qr', max_length=50),
        ),
    ]
