# Generated by Django 6.1 on 2026-09-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_chapters_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('credential', models.CharField(editable=False, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('scanned', 'Scanned'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_substitutes', to='credentials.employeecredential')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='credentials.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'member', 'name'), name='unique_substitute_per_session_member')],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('credential', models.CharField(editable=False, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('scanned', 'Scanned'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_visitors', to='credentials.employeecredential')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='credentials.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'member', 'name'), name='unique_visitor_per_session_member')],
            },
        ),
    ]
